---
title: "Untitled"
author: "Tom Klotz"
date: "19 4 2023"
output: html_document
---
```{r}
library(ggplot2)
library(factoextra)
library(FactoMineR)
library(here)
library(wordcloud2)
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
```

### Wortcluster

```{r}
df_aberwitzig <- df[df$pattern == "aberwitzig(e|er|es|en|em)?",]


tdm <- tm::DocumentTermMatrix(df_aberwitzig$sentence)
#findFreqTerms(tdm, lowfreq = 4)
```


```{r}
tdm.tfidf <- tm::weightTfIdf(tdm)
tdm.tfidf <- tm::removeSparseTerms(tdm.tfidf, 0.999) 
tfidf.matrix <- as.matrix(tdm.tfidf) 
# Cosine distance matrix (useful for specific clustering algorithms) 
dist.matrix = proxy::dist(tfidf.matrix, method = "cosine")
```

### Clustering
```{r}
truth.K = 2  # wie viele dimensionen?

clustering.kmeans <- kmeans(tfidf.matrix, truth.K, iter.max = 10, nstart = 2)

print(clustering.kmeans)
```

```{r}
clustering.kmeans$cluster

df_aberwitzig$cluster <- clustering.kmeans$cluster

df_aberwitzig_cluster1 <- df_aberwitzig[df_aberwitzig$cluster == 1,]
df_aberwitzig_cluster2 <- df_aberwitzig[df_aberwitzig$cluster == 2,]
```


```{r}
dtm <- TermDocumentMatrix(df_aberwitzig_cluster1$sentence)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)


set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```

```{r}
dtm <- TermDocumentMatrix(df_aberwitzig_cluster2$sentence)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)


set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```


```{r}
?wordcloud2


wordcloud2(data=df_aberwitzig_cluster1, size = 0.7, shape = 'pentagon')
```

















```{r}
fviz_cluster(data = df_aberwitzig,
            clustering.kmeans)



```

