---
title: "Test_Script"
author: "Tom Klotz"
date: "9 6 2023"
output: html_document
---

```{r}
corp <- corpus(df2017, text_field = "speech_content")
```


```{r}
greeting_phrases <- c("liebe frau präsidentin","lieber herr präsident","herr präsident","frau präsidentin","sehr geehrter","sehr geehrte","liebe kolleginnen und kollegen","meine sehr verehrten damen und herren","verehrte kolleginnen und kollegen","geehrte kolleginnen und kollegen","herr parlamentspräsident","frau parlamentspräsidentin","herr minister","frau ministerin","herr staatssekretär","frau staatssekretärin","herr alterspräsident","frau altpräsidentin")


corpus_preparation <- function(dataframe){
  corp <- corpus(dataframe$speech_content, docvars = data.frame(docname = dataframe$id, party = dataframe$party))
  toks <- tokens(corp, remove_punct = T, remove_symbols = T, remove_numbers = T, remove_url = TRUE,
                 remove_separators = T, include_docvars = T, split_hyphens = F)
  toks <- tokens_tolower(toks, keep_acronyms = FALSE)
  toks <- tokens_remove(toks, stopwords("german"))
  toks <- tokens_remove(toks, greeting_phrases)
  toks_compund <- get_pop_tokens_updated(
    corp,
    create_compounds = T,
    compounds_at_level = "sentences",
    compounds_dict = popdictR::gruendl_terms,
    compounds_dict_glob = FALSE
  )
  corp <- vapply(toks_compund, paste, FUN.VALUE = character(1), collapse = " ") %>%
    corpus()
  df <- cbind(corp, docvars(toks)) 
  rownames(df) <- df$docname
  assign("docvars", df,  envir = globalenv()) # für corpus_to_poppulism_context_df
  corp <- corpus(docvars, text_field = "corp")
}
```


```{r}
expertyears_cleaning <- function(corp, pattern){
  toks <- get_pop_tokens_updated(corp,create_compounds = T,compounds_dict = pattern,compounds_at_level = "sentences")
  docnames(toks) <- docvars(corp)$id
  docvars(toks)$party <- docvars(corp)$party
  docvars(toks)$n_sentences <- quanteda::nsentence(corp)
  docvars(toks)$n_tokens <- quanteda::ntoken(toks)
  return(toks)
}


```


```{r}
 df_kwic <- kwic(corp, pattern = terms, valuetype = "regex", window = 5) #window 
  #combine pre and after
  df_kwic$context <- paste(df_kwic$pre, df_kwic$post, sep = " ")
  df_kwic <- as.data.frame(df_kwic) %>% select(docname,pattern,context)
  docvars$corp <- NULL #aus corpus cleaning
  docvars$docname  <- as.character(docvars$docname)
  df_complete <- merge(df_kwic, docvars) #add party colum
```





### Gruendl


```{r}
popres <- popdictR::run_popdict(corp)
popres <- convert(popres, to = "data.frame")

sum(popres$dict_gruendl_2020)
```

### Mein underscore


```{r}
df_kwic <- kwic(corp_2017_clean, pattern = gruendl_patterns_to_underscore()  , valuetype = "regex", window = 1, case_insensitive = T)
df_kwic <- kwic(corp_2017_clean, pattern =  gruendl_patterns_to_compound  , valuetype = "regex", window = 1, case_insensitive = T)
```











#


