---
title: "Untitled"
author: "Tom Klotz"
date: "11 6 2023"
output: html_document
---

```{r}
df_kwic2 <- kwic(corp_clean, pattern = "\\b(wollen|ein?fordern|möchten|mögen|verlangen|beanspruchen|wünschen) (.*? )?arbeiter(?:innen)?\\b", valuetype = "regex", window = 1, case_insensitive = TRUE)


df_kwic2 <- kwic(corp, pattern = phrase("(wollen|(ein)?fordern|möchten|mögen|verlangen|beanspruchen|wünschen)\\s(.*\\s)?bürger(innen)?"), valuetype = "regex", window = 1, case_insensitive = TRUE)

####teste   kwic error

d <- dictionary(list(populismus =  phrase("\\bwünschen arbeiter(?:innen)?\\b
")))

df_kwic2 <- kwic(corp, pattern = d, valuetype = "regex", window = 1, case_insensitive = TRUE)

t <- kwic(corp, pattern = phrase("\\b(wollen|ein?fordern|möchten|mögen|verlangen|beanspruchen|wünschen) (.*? )?arbeiter(?:innen)?\\b"), valuetype = "regex", window = 2)


multidictR::
```

```{r}
dfm <- dfm(corp_clean)

dfm <- quanteda::dfm_weight(dfm, "boolean")
        dfm <- quanteda::dfm_group(
          dfm,
          groups = quanteda::docid(dfm),
          fill = TRUE,
          force = TRUE
        )
        
summary(dfm)

corp <- dfm_convert(dfm, to = "corpus")

docs <- convert(dfm, to = "text")
```


```{r}
#Dictionary context
### Main terms
t <- popdictR::gruendl_dictionary_complete
terms_total <- popdictR::gruendl_dictionary_complete %>% select(Word,Sub_Type,Comment,duplicate, real_duplicate,wildcard,multiword)

terms_total$filter <- ifelse(terms_total$Word %in% terms, 1,0)
table(terms_total$filter)

terms_df <- terms_total[terms_total$filter ==1,]

terms_multiword <- terms_df[terms_df$multiword == T,]

terms_non_multi <- terms_df[terms_df$multiword == F,]
terms_non_multi$word_regex <- regexhelpeR::make_all_regex_lazy(terms_non_multi$Word)
terms_non_multi$word_regex<- regexhelpeR::optimize_regex_patterns(terms_non_multi$word_regex)


terms_adjusted <- stringi::stri_replace_all_fixed(terms_multiword$Word , " ", "\\s")
terms_adjusted  <- c(terms_non_multi$Word, terms_adjusted)

terms_adjusted <- regexhelpeR::make_all_regex_lazy(terms_adjusted)
terms_adjusted <- regexhelpeR::optimize_regex_patterns(terms_adjusted)

df_kwic2 <- kwic(corp_clean, pattern = terms_adjusted, valuetype = "regex", window = 1, case_insensitive = T)
#compund2 1990 #documents 1990

df_kwic2 <- kwic(corp_clean, pattern = terms_non_multi$word_regex, valuetype = "regex", window = 1, case_insensitive = T)
#compund2 1990 #documents 1990

table(df_kwic2$pattern)
table(df_kwic3$pattern)


```