#Libraries
library(RPostgres)
library(RPostgreSQL)
library(quanteda)
library(udpipe)
library(proxy)
library(ggplot2)
library(tidyverse)
library(proxy)
library(factoextra)
library(FactoMineR)
library(here)
library(devtools)
library(proxyC)
library(tidytext)
library(manifestoR)
devtools::install_github("jogrue/regexhelpeR")
devtools::install_github("jogrue/multidictR")
devtools::install_github("jogrue/popdictR")


