---
title: "Prep"
author: "Tom Klotz"
date: "3 5 2023"
output: html_document
---
 
### Preprocessing
 
### Main dict


##########################
#Pre_processing updated
##########################



```{r}
greeting_phrases <- c("liebe frau präsidentin","lieber herr präsident","herr präsident","frau präsidentin","sehr geehrter","sehr geehrte","liebe kolleginnen und kollegen","meine sehr verehrten damen und herren","verehrte kolleginnen und kollegen","geehrte kolleginnen und kollegen","herr parlamentspräsident","frau parlamentspräsidentin","herr minister","frau ministerin","herr staatssekretär","frau staatssekretärin","herr alterspräsident","frau altpräsidentin","meine damen und herren","liebe neue kolleginnen und kollegen")
```

```{r}
#BT17

corpBT17 <- corpus(BT17, text_field = "speech_content")
for (i in greeting_phrases) {
  corpBT17 <- gsub(i,"",corpBT17, ignore.case = T) #remove greeting phrases
}
tokensBT17 <- corpus_to_compound_tokens(corpBT17, popdictR::gruendl_terms) #create compound tokens for multiwords
contextBT17 <- aggregate_context(tokensBT17, gruendl_patterns_to_underscore()) #create context vector 
saveRDS(contextBT17, file = "contextBT17.RDS")
contextBT17_clean <- clean_contextdata(contextBT17$context)
distBT17_euclidean <- distance_matrix(contextBT17_clean, method = "euclidean") 
saveRDS(distBT17_euclidean, file = "distBT17_euclidean.RDS")



#BT18
corpBT18 <- corpus(BT18, text_field = "speech_content")
for (i in greeting_phrases) {
  corpBT18 <- gsub(i,"",corpBT18, ignore.case = T)
}
tokensBT18 <- corpus_to_compound_tokens(corpBT18, popdictR::gruendl_terms)
contextBT18 <- aggregate_context(tokensBT18, gruendl_patterns_to_underscore())
saveRDS(contextBT18, file = "contextBT18.RDS")
contextBT18_clean <- clean_contextdata(contextBT18$context)
distBT18_euclidean <- distance_matrix(contextBT18_clean, method = "euclidean")
saveRDS(distBT18_euclidean, file = "distBT18_euclidean.RDS")


#BT19

corpBT19 <- corpus(BT19, text_field = "speech_content")
for (i in greeting_phrases) {
  corpBT19 <- gsub(i,"",corpBT19, ignore.case = T)
}
tokensBT19 <- corpus_to_compound_tokens(corpBT19, popdictR::gruendl_terms)
contextBT19 <- aggregate_context(tokensBT19, gruendl_patterns_to_underscore())
saveRDS(contextBT19, file = "contextBT19.RDS")
contextBT19_clean <- clean_contextdata(contextBT19$context)
distBT19_euclidean <- distance_matrix(contextBT19_clean, method = "euclidean")
saveRDS(distBT19_euclidean, file = "distBT19_euclidean.RDS")


#BT20
corpBT20 <- corpus(BT20, text_field = "speech_content")
for (i in greeting_phrases) {
  corpBT20 <- gsub(i,"",corpBT20, ignore.case = T)
}
tokensBT20 <- corpus_to_compound_tokens(corpBT20, popdictR::gruendl_terms)
contextBT20 <- aggregate_context(tokensBT20, gruendl_patterns_to_underscore())
saveRDS(contextBT20, file = "contextBT20.RDS")
contextBT20_clean <- clean_contextdata(contextBT20$context)
distBT20_euclidean <- distance_matrix(contextBT20_clean, method = "euclidean")
saveRDS(distBT20_euclidean, file = "distBT20_euclidean.RDS")



```
