---
title: "3.5 Statistiken gewichteter Diktionäre"
author: "Tom Klotz"
date: "9 7 2023"
output: html_document
---



### Anwendung

```{r}
corpBT17_20 <- corpus(BT17_20, text_field = "speech_content")
toksBT17_20_clean <- get_pop_tokens_updated(corpBT17_20,create_compounds = T,compounds_dict = popdictR::gruendl_terms,compounds_at_level = "sentences")
saveRDS(toksBT17_20_clean, file = "toksBT17_20_clean.RDS")
```

```{r}

stats <- weightdictR::get_pattern_stats(toksBT17_20_clean, gruendl_patterns_to_compound(), regex = TRUE)
stats <- merge(stats, dfClara)
saveRDS(stats, file = "dfClaraMatchcount.RDS")

maxstats <- stats[stats$match_count >= 10,]
maxstats <- maxstats[order(-maxstats$weight),]

head(maxstats$pattern, 5) #höchste Gewichtung
tail(maxstats$pattern, 5) #niedrigste Gewichtung
```



#### Max

```{r}
patterns_max <- c("\\bnomenklatura\\b","\\bsagen_dürfen\\b","\\bschande\\b","\\bfrechheit\\b","\\bbürgerfern(e|er|es|en|em)??\\b")

kwicMax <- kwic(toksBT17_20_clean, patterns_max, valuetype = "regex", window = 15)

#corpBT17_20[docnames(corpBT17_20) == "text80383"][[1]]
#corpBT17_20[docnames(corpBT17_20) == "text55829"][[1]]
#corpBT17_20[docnames(corpBT17_20) == "text5843"][[1]]
#corpBT17_20[docnames(corpBT17_20) == "text63834"][[1]]
#corpBT17_20[docnames(corpBT17_20) == "text69158"][[1]]
#corpBT17_20[docnames(corpBT17_20) == "text76406"][[1]]
#corpBT17_20[docnames(corpBT17_20) == "text72726"][[1]]
#corpBT17_20[docnames(corpBT17_20) == "text44494"][[1]]
#corpBT17_20[docnames(corpBT17_20) == "text66331"][[1]]
#corpBT17_20[docnames(corpBT17_20) == "text7061"][[1]]

table(kwicMax$keyword)
```

#### Min

```{r}
patterns_min <- c("\\bauf_kosten_de(s|r)_deutsche(n|r)\\b","\\bauf_kosten_der_allgemeinheit\\b","\\bwahnwitzig(e|er|es|en|em)??\\b","\\bzu(_)??lasten_de(s|r)_deutsche(n|r)\\b","\\bzum_schaden_de(s|r)\\b")

kwicMin <- kwic(toksBT17_20_clean, patterns_min, valuetype = "regex", window = 10)

corpBT17_20[docnames(corpBT17_20) == "text67915"][[1]]
corpBT17_20[docnames(corpBT17_20) == "text88183"][[1]]
corpBT17_20[docnames(corpBT17_20) == "text63121"][[1]]
corpBT17_20[docnames(corpBT17_20) == "text7097"][[1]]

table(kwicMin$keyword)
```


### Clara vs Clara without low frequent terms

##### Speeches


```{r}
minstats <- stats[stats$match_count < 10 & stats$match_count != 0,]

dfClara10 <- dfClara[!(dfClara$pattern %in% minstats$pattern),]


###2014 ------------------------------------------------------------------------

result2014Clara10 <- run_weighted_multiword_dict(
  data = corp_2014_clean,
  dict_compound = pattern,
  dict_name = "gruendl10",
  dict_weight = dfClara10,
  dict_weight_name = "clara10",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = FALSE
)

result2014Clara <- run_weighted_multiword_dict(
  data = corp_2014_clean,
  dict_compound = pattern,
  dict_name = "gruendl",
  dict_weight = dfClara,
  dict_weight_name = "clara",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = TRUE
)


result2014 <- bind_cols(result2014Clara,select(result2014Clara10, clara10, gruendl10))
                        

result2014$party[result2014$party == "DIE LINKE."] <- "LINKE"
result2014 <- na.omit(result2014)

for (i in c("gruendl","gruendl10", "clara","clara10")) {
  result2014[[i]] <- result2014[[i]] / result2014$n_sentences
  result2014[[i]] <- scale(result2014[[i]], center = T)
}

validation2014 <- merge(result2014, exp2014)

correlation2014 <- list()

for (i in c("gruendl","gruendl10", "clara","clara10")) {
    correlation <- cor(x = validation2014[[i]], y = validation2014$expert_rating, method = "pearson")
    correlation2014[[i]] <- correlation 
}

###2017 ------------------------------------------------------------------------

result2017Clara10 <- run_weighted_multiword_dict(
  data = corp_2017_clean,
  dict_compound = pattern,
  dict_name = "gruendl10",
  dict_weight = dfClara10,
  dict_weight_name = "clara10",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = FALSE
)

result2017Clara <- run_weighted_multiword_dict(
  data = corp_2017_clean,
  dict_compound = pattern,
  dict_name = "gruendl",
  dict_weight = dfClara,
  dict_weight_name = "clara",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = TRUE
)


result2017 <- bind_cols(result2017Clara,select(result2017Clara10, clara10, gruendl10))
                        

result2017$party[result2017$party == "DIE LINKE."] <- "LINKE"
result2017$party[result2017$party == "Fraktionslos"] <- NA
result2017 <- na.omit(result2017)

for (i in c("gruendl","gruendl10", "clara","clara10")) {
  result2017[[i]] <- result2017[[i]] / result2017$n_sentences
  result2017[[i]] <- scale(result2017[[i]], center = T)
}

validation2017 <- merge(result2017, exp2017)

correlation2017 <- list()

for (i in c("gruendl","gruendl10", "clara","clara10")) {
    correlation <- cor(x = validation2017[[i]], y = validation2017$expert_rating, method = "pearson")
    correlation2017[[i]] <- correlation 
}

###2019 ------------------------------------------------------------------------

result2019Clara10 <- run_weighted_multiword_dict(
  data = corp_2019_clean,
  dict_compound = pattern,
  dict_name = "gruendl10",
  dict_weight = dfClara10,
  dict_weight_name = "clara10",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = FALSE
)

result2019Clara <- run_weighted_multiword_dict(
  data = corp_2019_clean,
  dict_compound = pattern,
  dict_name = "gruendl",
  dict_weight = dfClara,
  dict_weight_name = "clara",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = TRUE
)


result2019 <- bind_cols(result2019Clara,select(result2019Clara10, clara10, gruendl10))
                      

result2019$party[result2019$party == "DIE LINKE."] <- "LINKE"
result2019$party[result2019$party == "Fraktionslos"] <- NA
result2019 <- na.omit(result2019)

for (i in c("gruendl","gruendl10", "clara","clara10")) {
  result2019[[i]] <- result2019[[i]] / result2019$n_sentences
  result2019[[i]] <- scale(result2019[[i]], center = T)
}

validation2019 <- merge(result2019, exp2019)

correlation2019 <- list()

for (i in c("gruendl","gruendl10", "clara","clara10")) {
    correlation <- cor(x = validation2019[[i]], y = validation2019$expert_rating, method = "pearson")
    correlation2019[[i]] <- correlation 
}

###Grafik ----------------------------------------------------------------------

Jahr <- c(2014,2017,2019,"Durchschnitt")
gruendl_mean <- (correlation2014$gruendl + correlation2017$gruendl + correlation2019$gruendl)/3
gruendl <- round(c(correlation2014$gruendl, correlation2017$gruendl, correlation2019$gruendl, gruendl_mean), digits = 3)

gruendl_mean10 <- (correlation2014$gruendl10 + correlation2017$gruendl10 + correlation2019$gruendl10)/3
gruendl10 <- round(c(correlation2014$gruendl10, correlation2017$gruendl10, correlation2019$gruendl10, gruendl_mean10), digits = 3)

clara_mean <- (correlation2014$clara + correlation2017$clara + correlation2019$clara)/3
clara <- round(c(correlation2014$clara, correlation2017$clara, correlation2019$clara, clara_mean), digits = 3)

clara_mean10 <- (correlation2014$clara10 + correlation2017$clara10 + correlation2019$clara10)/3
clara10 <- round(c(correlation2014$clara10, correlation2017$clara10, correlation2019$clara10, clara_mean10), digits = 3)
               
              

dfValidation <- data.frame(Jahr, gruendl, gruendl10, clara, clara10)


gtValidation <- gt(dfValidation,rowname_col = "Jahre") %>%  
  tab_header(
   title = "Tabelle 1: Dictionaries im Vergleich ",
   subtitle = "Zusammenhang zwischen Dictionaries und Expertenbefragungen nach Jahren") %>%
   gtsave("speechesValidation10.tex")

```

#### MP


```{r}
minstats <- stats[stats$match_count < 10 & stats$match_count != 0,]

dfClara10 <- dfClara[!(dfClara$pattern %in% minstats$pattern),]


###2013 ------------------------------------------------------------------------

result2013Clara10 <- run_weighted_multiword_dict(
  data = mp2013Clean,
  dict_compound = pattern,
  dict_name = "gruendl10",
  dict_weight = dfClara10,
  dict_weight_name = "clara10",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = FALSE
)

result2013Clara <- run_weighted_multiword_dict(
  data = mp2013Clean,
  dict_compound = pattern,
  dict_name = "gruendl",
  dict_weight = dfClara,
  dict_weight_name = "clara",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = TRUE
)


result2013 <- bind_cols(result2013Clara,select(result2013Clara10, clara10, gruendl10))
                        

result2013$party[result2013$party == "DIE LINKE."] <- "LINKE"
result2013 <- na.omit(result2013)

for (i in c("gruendl","gruendl10", "clara","clara10")) {
  result2013[[i]] <- result2013[[i]] / result2013$n_sentences
  result2013[[i]] <- scale(result2013[[i]], center = T)
}

validation2013 <- merge(result2013, exp2014_afd)

correlation2013 <- list()

for (i in c("gruendl","gruendl10", "clara","clara10")) {
    correlation <- cor(x = validation2013[[i]], y = validation2013$expert_rating, method = "pearson")
    correlation2013[[i]] <- correlation 
}

###2017 ------------------------------------------------------------------------

result2017Clara10 <- run_weighted_multiword_dict(
  data = mp2017Clean,
  dict_compound = pattern,
  dict_name = "gruendl10",
  dict_weight = dfClara10,
  dict_weight_name = "clara10",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = FALSE
)

result2017Clara <- run_weighted_multiword_dict(
  data = mp2017Clean,
  dict_compound = pattern,
  dict_name = "gruendl",
  dict_weight = dfClara,
  dict_weight_name = "clara",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = TRUE
)


result2017 <- bind_cols(result2017Clara,select(result2017Clara10, clara10, gruendl10))
                        

result2017$party[result2017$party == "DIE LINKE."] <- "LINKE"
result2017 <- na.omit(result2017)

for (i in c("gruendl","gruendl10", "clara","clara10")) {
  result2017[[i]] <- result2017[[i]] / result2017$n_sentences
  result2017[[i]] <- scale(result2017[[i]], center = T)
}

validation2017 <- merge(result2017, exp2017)

correlation2017 <- list()

for (i in c("gruendl","gruendl10", "clara","clara10")) {
    correlation <- cor(x = validation2017[[i]], y = validation2017$expert_rating, method = "pearson")
    correlation2017[[i]] <- correlation 
}

###2021 ------------------------------------------------------------------------

result2021Clara10 <- run_weighted_multiword_dict(
  data = mp2021Clean,
  dict_compound = pattern,
  dict_name = "gruendl10",
  dict_weight = dfClara10,
  dict_weight_name = "clara10",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = FALSE
)

result2021Clara <- run_weighted_multiword_dict(
  data = mp2021Clean,
  dict_compound = pattern,
  dict_name = "gruendl",
  dict_weight = dfClara,
  dict_weight_name = "clara",
  prepare_corp = FALSE,
  include_main_dict = TRUE,
  include_totals = TRUE
)


result2021 <- bind_cols(result2021Clara,select(result2021Clara10, clara10, gruendl10))
                        

result2021$party[result2021$party == "DIE LINKE."] <- "LINKE"
result2021 <- na.omit(result2021)

for (i in c("gruendl","gruendl10", "clara","clara10")) {
  result2021[[i]] <- result2021[[i]] / result2021$n_sentences
  result2021[[i]] <- scale(result2021[[i]], center = T)
}

validation2021 <- merge(result2021, exp2019)

correlation2021 <- list()

for (i in c("gruendl","gruendl10", "clara","clara10")) {
    correlation <- cor(x = validation2021[[i]], y = validation2021$expert_rating, method = "pearson")
    correlation2021[[i]] <- correlation 
}

###Grafik ----------------------------------------------------------------------

Jahr <- c(2013,2017,2021,"Durchschnitt")
gruendl_mean <- (correlation2013$gruendl + correlation2017$gruendl + correlation2021$gruendl)/3
gruendl <- round(c(correlation2013$gruendl, correlation2017$gruendl, correlation2021$gruendl, gruendl_mean), digits = 3)

gruendl_mean10 <- (correlation2013$gruendl10 + correlation2017$gruendl10 + correlation2021$gruendl10)/3
gruendl10 <- round(c(correlation2013$gruendl10, correlation2017$gruendl10, correlation2021$gruendl10, gruendl_mean10), digits = 3)

clara_mean <- (correlation2013$clara + correlation2017$clara + correlation2021$clara)/3
clara <- round(c(correlation2013$clara, correlation2017$clara, correlation2021$clara, clara_mean), digits = 3)

clara_mean10 <- (correlation2013$clara10 + correlation2017$clara10 + correlation2021$clara10)/3
clara10 <- round(c(correlation2013$clara10, correlation2017$clara10, correlation2021$clara10, clara_mean10), digits = 3)
               
              

dfValidation <- data.frame(Jahr, gruendl, gruendl10, clara, clara10)


gtValidation <- gt(dfValidation,rowname_col = "Jahre") %>%  
  tab_header(
   title = "Tabelle 1: Dictionaries im Vergleich ",
   subtitle = "Zusammenhang zwischen Dictionaries und Expertenbefragungen nach Jahren") %>%
   gtsave("mpValidation10.tex")

```

