---
title: "Untitled"
author: "Tom Klotz"
date: "25 5 2023"
output: html_document
---

## Expertendaten
CHES prpearation for 2014 and 2019

```{r}
df <- read_csv("./Expertendaten/1999-2019_CHES_dataset_means(v3).csv")

#3 = Germany
df <- df[df$country ==3,]

exp <- df %>% select(c("party","year","electionyear","people_vs_elite","antielite_salience"))
```


### CHES 2019
```{r}
exp_2019 <- filter(df, year == 2019 ) %>%
            select(c("party","people_vs_elite","antielite_salience"))

#Kodierung Bündnis90 die Grünen anpassen
exp_2019$party[exp_2019$party == "GRUNEN"] <- "Grüne"

#Kodierung an Fraktion CDU/CSU anpassen
mean_CDUCSU_salience <- (exp_2019$antielite_salience[exp_2019$party == "CDU"] + exp_2019$antielite_salience[exp_2019$party == "CSU"])/2

mean_CDUCSU_people_vs_elite <- (exp_2019$people_vs_elite[exp_2019$party == "CDU"] + exp_2019$people_vs_elite[exp_2019$party == "CSU"])/2

exp_2019$antielite_salience[exp_2019$party == "CDU"] <- mean_CDUCSU_salience
exp_2019$people_vs_elite[exp_2019$party == "CDU"] <- mean_CDUCSU_people_vs_elite

exp_2019$party[exp_2019$party == "CDU"] <- "CDU/CSU"

#Parteien im Bundestag 2019 auswählen
exp_2019 <- exp_2019 %>% filter(party %in% c("CDU/CSU","SPD","Grüne","LINKE","AfD","FDP"))

#rowMeans Indexbildung und Z-Transformation
exp_2019$expert_rating <- as.numeric(rowMeans(exp_2019[c("people_vs_elite","antielite_salience")],))
exp_2019$expert_rating_z <- scale(exp_2019$expert_rating, center = T)

#Remove
exp_2019$antielite_salience <- NULL
exp_2019$people_vs_elite <- NULL

saveRDS(exp_2019, file = "exp2019.RDS")
```

### CSES 2017
#### Party identifier from project manifesto database

```{r}
mp <- read_csv("./Expertendaten/MPDataset_MPDS2022a.csv")


table(mp$countryname)

mp <- mp[mp$countryname == "Germany",]
manifestoR::mp_setapikey("./Expertendaten/manifesto_apikey.txt")

mp <- mp %>% group_by(partyabbrev) %>%
  reframe(party_id = party)

mp

#Index für CSES Datensatz

# CDU/CSU 41521
# SPD 41320
# AfD 41953
# FDP 41420
# LINKE 41223
# Grüne 41113

###Apply to CSES dataframe --------------------

load("~/Documents/Uni Stuttgart/BachelorarbeitPopulismus/Code/Expertendaten/cses5.rdata")



cses <- cses5 %>% 
  rename(country = E1003) %>%
  filter(country == 27602017) #Germany

#manifesto party identifier
table(cses$E5200_A) #CDU
table(cses$E5200_B) #SPD
table(cses$E5200_C) #AfD
table(cses$E5200_D) #FDP
table(cses$E5200_E) #Linke
table(cses$E5200_F) #Grüne
table(cses$E5200_G) #CSU




cses <- cses %>%
  select(country,starts_with("E5020")) %>% #Populism expert rating
  rename(CDU = E5020_A, SPD = E5020_B, AfD = E5020_C, FDP = E5020_D, LINKE = E5020_E, Grüne = E5020_F, CSU = E5020_G) %>%         select(CDU, SPD, AfD, FDP, LINKE, Grüne, CSU)

#Fraktion CDU/CSU
cses$'CDU/CSU' <- (cses$CDU + cses$CSU)/2
cses$CDU <- NULL
cses$CSU <- NULL

#Konstruktion des gewünschten Daframe-Formats
exp_2017 <- as.data.frame(t(cses))
exp_2017 <- exp_2017 %>% rename(expert_rating = '18515') %>% select(expert_rating)
exp_2017$expert_rating_z <- scale(exp_2017$expert_rating, center = T)
exp_2017$party <- rownames(exp_2017)

saveRDS(exp_2017, file = "exp2017.RDS")
```

### CHES 2014

```{r}

exp_2014 <- filter(df, year == 2014 ) %>%
            select(c("party","antielite_salience"))

#Kodierung Bündnis90 die Grünen anpassen
exp_2014$party[exp_2014$party == "Grunen"] <- "Grüne"

#Kodierung an Fraktion CDU/CSU anpassen
mean_CDUCSU <- (exp_2014$antielite_salience[exp_2014$party == "CDU"] + exp_2014$antielite_salience[exp_2014$party == "CSU"])/2

exp_2014$antielite_salience[exp_2014$party == "CDU"] <- mean_CDUCSU
exp_2014$party[exp_2014$party == "CDU"] <- "CDU/CSU" 


#Parteien im Bundestag 2014 auswählen
exp_2014 <- exp_2014 %>% filter(party %in% c("CDU/CSU","SPD","Grüne","LINKE"))
exp_2014_afd <- exp_2014 %>% filter(party %in% c("CDU/CSU","SPD","Grüne","LINKE","AfD"))

#Z-Transformation
exp_2014$expert_rating <- as.numeric(exp_2014$antielite_salience)
exp_2014$expert_rating_z <- scale(exp_2014$expert_rating, center = T)

#Remove
exp_2014$antielite_salience <- NULL


saveRDS(exp_2014, file = "exp2014.RDS")

```

### CHES 2014 AfD


```{r}
exp_2014_afd <- exp_2014 %>% filter(party %in% c("CDU/CSU","SPD","Grüne","LINKE","AfD"))

#Z-Transformation
exp_2014_afd$expert_rating <- as.numeric(exp_2014_afd$antielite_salience)
exp_2014_afd$expert_rating_z <- scale(exp_2014_afd$expert_rating, center = T)

#Remove
exp_2014_afd$antielite_salience <- NULL


saveRDS(exp_2014_afd, file = "exp2014_afd.RDS")

```

##############################
## Visualiserung Experteneinordnungen
##############################



```{r}
expResults <- merge(merge(exp2014_afd, exp2017, by = "party"), exp2019, by = "party")
colnames(expResults) <- c("Partei", "2014","2014_z","2017","2017_z","2019","2019_z")

expResults$`2014` <- round(expResults$`2014`, digits = 2)
expResults$`2014_z` <- round(expResults$`2014_z`, digits = 2)
expResults$`2017_z` <- round(expResults$`2017_z`, digits = 2)
expResults$`2019` <- round(expResults$`2019`, digits = 2)
expResults$`2019_z` <- round(expResults$`2019_z`, digits = 2)

gtExpert <- gt(expResults) %>%  
  tab_header(
   title = "Tabelle 1: Populismuseinordnung der Parteien nach Expertenbefragungen")
   #gtsave("gtValidation.tex")
```
 
