---
title: "Untitled"
author: "Tom Klotz"
date: "15 4 2023"
output: html_document
---

```{r}
library(quanteda)
devtools::install_github("jogrue/regexhelpeR")
devtools::install_github("jogrue/multidictR")
devtools::install_github("jogrue/popdictR")
```

```{r}
terms <- popdictR::gruendl_terms

```


### Quanteda Dict
```{r}
#dict <- dictionary(as.list(test))
test <- c("Hallo","Hello","Danke")


```

### Corpus

#### Testing
Anwendung anderer Diktionäre funktioniert...aber esgibt keine Möglichkeit eine Gewichtung vorzumehmen
```{r}
corp_test <- corpus(testing, text_field = "speech_content")




result <- multidictR::run_multidict(corpus = corp_test, dict = terms_kmeans, at_level = "sentences", return_value = c(
    "count",
    "binary",
    "prop",
    "count_at_level",
    "prop_at_level"
  ), pattern_type = c("regex"), return_result_only = F, dict_name = "gruendl", stem = T)

result2 <- convert(result, to = "data.frame")



```

```{r}
result <- popdictR::run_popdict(corpus = corp_test)
result1 <- convert(result, to = "data.frame")
```

### Tidytext experiment
```{r}
library(remotes)
library(textdata)
library(tidydata)
install.packages("tidydata")
install_github("juliasilge/tidytext")

textdata::lexicon_afinn()
```

