---
title: "Test_Script"
author: "Tom Klotz"
date: "9 6 2023"
output: html_document
---


### Pre Processing
```{r}
library(quanteda)
library(tidyverse)
devtools::install_github("jogrue/regexhelpeR")
devtools::install_github("jogrue/multidictR")
devtools::install_github("jogrue/popdictR")
```


```{r}
df <- readRDS("~/Documents/Uni Stuttgart/BachelorarbeitPopulismus/Code/TestData.RDS") #Pfad anpassen
corp <- corpus(df_2014, text_field = "speech_content")

toks <- tokens(corp, remove_punct = T, remove_symbols = T, remove_numbers = T,remove_url = TRUE,
      remove_separators = T, include_docvars = T, split_hyphens = F) #sep is true !!!!!!!
toks <- tokens_tolower(toks, keep_acronyms = FALSE)
#do not remove stoppwords
corp_clean <- vapply(toks, paste, FUN.VALUE = character(1), collapse = " ") %>%
  corpus()

#corp_clean_underscore <- stringi::stri_replace_all_fixed(corp_clean," ", "_")

```

### Dictionary


### KWIC

```{r}
#Regex Patterns anpassen mit omptimize und lazy
terms <- popdictR::gruendl_terms#dict_fixed$populismus
terms_optimized <- regexhelpeR::make_all_regex_lazy(terms)
terms_optimized <- regexhelpeR::optimize_regex_patterns(terms_optimized)

dict <- dictionary(list(populismus = terms_optimized))

df_kwic2 <- kwic(corp_clean, pattern = terms_optimized , valuetype = "regex", window = 1, case_insensitive = T)
df_kwic1 <- kwic(corp_clean, pattern = phrase("auf kosten der allgemeinheit"), valuetype = "regex", window = 1, case_insensitive = T)
```


### !!!Problem!!!

```{r}
sum(result1$dict_gruendl_2020) == length(df_kwic$docname)

#Sollte true sein, da regex patterns identisch sind
```


Das funktioniert wiederum...

```{r}
sum(stringi::stri_detect_regex(result1[3,2],pattern = dict$populismus, case_insensitive = T) == T) == 1
```

...führt aber auch nicht zu dem erwarteten Ergebnis
```{r}
i = 1
count = 0 
while (i < 105) {
  if (count == 0) {
    res <- stringi::stri_detect_regex(result1[i,2],pattern = as.vector(dict), case_insensitive = T) #quanteda::dictionary(list(populismus = dict))
    count = sum(res == TRUE)
    i = i + 1
  }
  else {
    res <- stringi::stri_detect_regex(result1[i,2],pattern = dict, case_insensitive = T)
    count = count + sum(res == TRUE)
    i = i +1
    
  }
 
 
}
 print(count)
 
 
 sum(result1$dict_gruendl_2020) == count #Sollte True sein
```

### Multidict nachbauen

```{r}
dict <- dictionary(list(populismus = popdictR::gruendl_terms))
dict <- unlist(dict)
dict <- regexhelpeR::optimize_regex_patterns(dict)
dict <- regexhelpeR::make_all_regex_lazy(dict)




 set.seed(17062005)
    replacement <- paste0(
      paste0(sample(letters, 20, replace = TRUE), collapse = ""),
      round(stats::runif(1, 1000000000, 9999999999), 0),
      paste0(sample(letters, 20, replace = TRUE), collapse = "")
    )
      

 for (i in dict) {
      quanteda::texts(corp_clean) <- stringr::str_replace_all(
        quanteda::texts(corp_clean),
        pattern = stringr::regex(i, ignore_case = T),
       replacement = replacement
      )
 }
  
    
    
    lookup_dict <- list(paste0("*", replacement, "*"))
    names(lookup_dict) <- "test"
    lookup_dict <- quanteda::dictionary(lookup_dict)
   
   #stringr::rege
    
    
dfm <- quanteda::dfm(corp)
dfm <- quanteda::dfm_lookup(
        dfm,
        dictionary = lookup_dict,
        valuetype = "glob",
        case_insensitive = T)

df_res <-      quanteda::convert(dfm, to = "data.frame")

sum(df_res$test)

dfm <- quanteda::dfm(corp_clean)
dfm <- quanteda::dfm_lookup(
        dfm, dictionary = quanteda::dictionary(list(populismus = dict)), valuetype = regex, case_insensitive = T)

sum(df_res$test)

df_kwic2 <- kwic(corp_clean, pattern = quanteda::dictionary(list(populismus = dict)) , valuetype = "regex", window = 1, case_insensitive = T)






df_kwic2 <- kwic(corp_clean, pattern = "\\b(wollen|ein?fordern|möchten|mögen|verlangen|beanspruchen|wünschen) (.*? )?arbeiter(?:innen)?\\b", valuetype = "regex", window = 1, case_insensitive = TRUE)


t <- stringi::stri_detect_regex(result1[1,2],pattern = dict, case_insensitive = T)


      
```


### Weitere Ideen ###



```{r}
#Dictionary context
### Main terms
terms <- popdictR::gruendl_terms

### Total considered terms

t <- popdictR::gruendl_dictionary_complete
terms_total <- popdictR::gruendl_dictionary_complete %>% select(Word,Sub_Type,Comment,duplicate, real_duplicate,wildcard,multiword)

terms_total$filter <- ifelse(terms_total$Word %in% terms, 1,0)
table(terms_total$filter)

terms_df <- terms_total[terms_total$filter ==1,]

terms_multiword <- terms_df[terms_df$multiword == T,]

#p <- terms_multiword[74,1]
#volk (.* )?(will|(ein)?fordert|möchte|mag|verlangt|beansprucht|wünscht)

stringr::str_replace_all("volk (.* )?(will|(ein)?fordert|möchte|mag|verlangt|beansprucht|wünscht)"," ", "_")
stringr::str_replace_all(terms_multiword[74,1]," ", "_")

terms_multiword$Word2 <- stringi::stri_replace_all_fixed(terms_multiword$Word,"(.* )?", "[^ ]* ") #für compund regex adjustment

terms_multiword$compund <- stringi::stri_replace_all_fixed(terms_multiword$Word," ", "_")
#terms_multiword$compund1 <- stringr::str_replace_all(terms_multiword$compund,"(.*_)", "(.*)")
terms_multiword$compund2 <- stringi::stri_replace_all_fixed(terms_multiword$compund, "(.*_)?", "[^_]*_")
terms_multiword$compund2 <- stringi::stri_replace_all_fixed(terms_multiword$compund2, "(_.*)?", "_[^_]") #kein Mehrwert
#terms_multiword$compund2 <- stringi::stri_replace_all_fixed(terms_multiword$compund2, "([^[:space:]]*?)", "[^_]*_") #kein Mehrwert



#(.*_) -> (.*)
#_[^_]*_
#_[^_]*_

compund_sentence <- make_compounds1(
  text = corp_clean,
  patterns = terms_multiword$Word2,
  wordsep = " ",
  concatenator = "_",
  at_level = "sentences", #documents?
  glob = FALSE,
  lazy = TRUE,
  ignore_case = TRUE,
  optimize_regex = TRUE)

compund_sentence2 <- make_compounds1(
  text = corp_clean,
  patterns = phrase(popdictR::gruendl_terms),
  wordsep = " ",
  concatenator = "_",
  at_level = "sentences", #documents?
  glob = FALSE,
  lazy = TRUE,
  ignore_case = TRUE,
  optimize_regex = TRUE)


compund_sentence3 <- get_pop_tokens1(
  corp,
  create_compounds = T,
  compounds_at_level = "sentences",
  compounds_dict = popdictR::gruendl_terms,
  compounds_dict_glob = FALSE
)
saveRDS(compund_sentence3, file = "compound_sentence2014.RDS")

compund_doc <- get_pop_tokens1(
  corp,
  create_compounds = T,
  compounds_at_level = "documents",
  compounds_dict = popdictR::gruendl_terms,
  compounds_dict_glob = FALSE
)

#dfm <- dfm(compund_sentence3)

compund_sentence2 == compund_sentence
#compund2[[24]]

########################### Create Dictionary
terms_df <- terms_df[terms_df$multiword == F,]
terms_ <- c(terms_df$Word, terms_multiword$compund) #change here!!!!!!!!!!!!!!!! for new regex words

terms_optimized <- regexhelpeR::optimize_regex_patterns(terms_)
terms_lazy <- regexhelpeR::make_all_regex_lazy(terms_optimized )

#terms_optimized_underscore <- stringi::stri_replace_all_fixed(terms_lazy , "\\b", "_") #for all underscore

#regexhelpeR::optimize_regex_patterns(regexhelpeR::make_all_regex_lazy("(wollen|(ein)?fordern|möchten|mögen|verlangen|beanspruc#hen|wünschen)_(.*_)?bürger(innen)?"))

df_kwic3 <- kwic(compund_doc, pattern = terms_lazy  , valuetype = "regex", window = 1, case_insensitive = T)
#compund 1990 #documents 1990

table(df_kwic3$pattern)

```
### Problemfälle
### neue?

\\b(aus)??verkauf(t|en)_([^[:space:]]*?)partei(en)??\\b" 

\\bso(-)??genannt(e|er|en)_([^[:space:]]*?)medien\\b" 

\\bfür_die_([^[:space:]]*?_)??mehrheit\\b"

 "\\betabliert(e|er|en)_([^[:space:]]*?)partei(en)??\\b"  
 
 \\bangeblich(e|er|en)??_([^[:space:]]*?)partei(en)??\\b"

### alte

[215] "(wollen|(ein)?fordern|möchten|mögen|verlangen|beanspruchen|wünschen)_(.*_)?arbeiter(innen)?"                                                         
[216] "(wollen|(ein)?fordern|möchten|mögen|verlangen|beanspruchen|wünschen)_(.*_)?bürger(innen)?"                                                           
[217] "(wollen|(ein)?fordern|möchten|mögen|verlangen|beanspruchen|wünschen)_(.*_)?steuerzahler(innen)?"                                                     
[218] "(wunsch|wünsche|anliegen|ansuchen|verlangen)_(der|einer|unserer)_bevölkerung"


### Test
```{r}
#"(wollen|(ein)?fordern|möchten|mögen|verlangen|beanspruchen|wünschen)_(.*_)?bürger(innen)?
df_kwic1 <- kwic(compund_sentence, pattern = phrase( "(wollen|(ein)?fordern|möchten|mögen|verlangen|beanspruchen|wünschen) [^_]* bürger(innen)?"), valuetype = "regex", window = 1, case_insensitive = T)
 
df_kwic1[3,5]
#(.*)
```


### Test 2014


```{r}
result1 <- popdictR::run_popdict(corp, dict_version = "current", at_level = "sentences", return_value = "count")

result2 <-  multidictR::run_multidict(
      corpus = corp,
      dict = dict,
      at_level = "sentences",
      return_value = "count_at_level",
      include_totals = TRUE,
      return_result_only = FALSE,
      pattern_type = "regex",
      case_insensitive = TRUE,
      regex_optimize = TRUE,
      regex_make_greedy = FALSE,
      regex_make_lazy = TRUE,
      dict_name = "gruendl_2",
      #custom_replacement = custom_replacement,
      tolower = TRUE,
      stem = FALSE,
      remove = NULL,
      what = "word",
      remove_punct = TRUE,
      remove_symbols = TRUE,
      remove_numbers = TRUE,
      remove_url = TRUE,
      remove_separators = F,
      split_hyphens = FALSE,
      include_docvars = TRUE)

result2 <- convert(result2, to = "data.frame")
result1 <- convert(result1, to = "data.frame")

result1 == result2

sum(result2$gruendl_2) #documents 1998 count_at_level # documents 1998 count #sentences 2024 count at level #sentences 2083
sum(result1$dict_gruendl_2020)


####Fehler identifizieren

dif <- result2[result2$gruendl_2 != 0,]

dif$filter <- ifelse(dif$doc_id %in% df_kwic3$docname,"good","difference")

dif <- dif[dif$filter == "difference",]
```



```{r}
#kwic_step <- multidictR::run_kwic_stepwise(toks, pattern = dict$populismus, window = 1, valuetype = "regex")

stats <- multidictR::get_pattern_stats(corp,
    popdictR::gruendl_terms,
    at_level = "documents", #sentence level
    glob = FALSE,
    ignore_case = T,
    optimize_regex = T)

sum(stats$match_count) #2095

text <- dif[56,2]

df_kwic_singlepattern <- kwic(text, pattern = popdictR::gruendl_terms, valuetype = "regex", window = 1, case_insensitive = T)
df_kwic_singlepattern <- kwic("das griechische Volk", pattern = popdictR::gruendl_terms, valuetype = "regex", window = 1, case_insensitive = T)

mehrheit <- c("mehrheit (der|im|in der|unter den|aller)","mehrheit (der|unter den|aller) bürger(n|innen)?", "mehrheit (des|im) volk(s|es|e)?","mehrheitsmeinung(en)?")
```

```{r}
i = 0
keyword <- NULL
pattern <- NULL
doc <- NULL
while (i < 57) {
  text <- dif[i,2]
  df_kwic_singlepattern <- kwic(text, pattern = regexhelpeR::make_all_regex_lazy(regexhelpeR::optimize_regex_patterns(popdictR::gruendl_terms)), valuetype = "regex", window = 1, case_insensitive = T)
  i = i + 1
  if (nrow(df_kwic_singlepattern) != 0){
    doc = append(doc, i)
    keyword = append(keyword, df_kwic_singlepattern$keyword)
    pattern = append(pattern, df_kwic_singlepattern$pattern)
  }
}
df_dif <- data.frame(keyword,pattern)





```

