---
title: "SQL_Datenabfragen"
author: "Tom Klotz"
date: "13 4 2023"
output: html_document
---

```{r}
library(RPostgres)
library(RPostgreSQL)
```

```{r, eval=FALSE}
# db_connection -----------------------------------------------------------
db <- "next"
host_db <- "localhost"
db_port <- "5432"
db_user <- "postgres"
db_password <- "postgres"
con <-
  RPostgreSQL::dbConnect(
    RPostgres::Postgres(),
    dbname = db,
    host = host_db,
    port = db_port,
    user = db_user,
    password = db_password
  )
?dbConnect
# get data tables ---------------------------------------------------------

df_2019 <- dbGetQuery(con,
                       "SELECT s.id,s.speech_content,s.date,f.abbreviation AS party
                        FROM open_discourse.speeches AS s
                        INNER JOIN open_discourse.factions AS f ON
                        s.faction_id = f.id
                        WHERE date BETWEEN '2019-01-01' AND '2019-12-31'
                        AND NOT abbreviation = 'not found';")

df_2017 <- dbGetQuery(con,
                       "SELECT s.id,s.speech_content,s.date,f.abbreviation AS party
                        FROM open_discourse.speeches AS s
                        INNER JOIN open_discourse.factions AS f ON
                        s.faction_id = f.id
                        WHERE date BETWEEN '2017-01-01' AND '2017-12-31'
                        AND NOT abbreviation = 'not found';")

df_2014 <- dbGetQuery(con,
                       "SELECT s.id,s.speech_content,s.date,f.abbreviation AS party
                        FROM open_discourse.speeches AS s
                        INNER JOIN open_discourse.factions AS f ON
                        s.faction_id = f.id
                        WHERE date BETWEEN '2014-01-01' AND '2014-12-31'
                        AND NOT abbreviation = 'not found';")



df_complete <- dbGetQuery(con,
                       "SELECT s.id,s.speech_content,s.date,f.abbreviation AS party
                        FROM open_discourse.speeches AS s
                        INNER JOIN open_discourse.factions AS f ON
                        s.faction_id = f.id
                        WHERE NOT abbreviation = 'not found';")

saveRDS(df_complete,file = "speeches_complete.RDS")
saveRDS(df_2014,file = "speeches_2014.RDS")
saveRDS(df_2017,file = "speeches_2017.RDS")
saveRDS(df_2019,file = "speeches_2019.RDS")







```


