---
title: "Untitled"
author: "Tom Klotz"
date: "13 6 2023"
output: html_document
---

### Dictionary context

```{r}
terms <- popdictR::gruendl_terms

### Total considered terms

t <- popdictR::gruendl_dictionary_complete
terms_total <- popdictR::gruendl_dictionary_complete %>% select(Word,Sub_Type,Comment,duplicate, real_duplicate,wildcard,multiword)

terms_total$filter <- ifelse(terms_total$Word %in% terms, 1,0)
table(terms_total$filter)

terms_df <- terms_total[terms_total$filter ==1,]
terms_multiword <- terms_df[terms_df$multiword == T,]


terms_multiword$compound <- stringi::stri_replace_all_fixed(terms_multiword$Word," ", "_")
terms_multiword$compound <- stringi::stri_replace_all_fixed(terms_multiword$compound,"(.*_)?", "[^_]*_")
terms_multiword$compound <- stringi::stri_replace_all_fixed(terms_multiword$compound, "(_.*)?", "_[^_]")



compund_sentence <- make_compounds1(
  text = corp_clean,
  patterns = popdictR::gruendl_terms,
  wordsep = " ",
  concatenator = "_",
  at_level = "sentences", #documents?
  glob = FALSE,
  lazy = TRUE,
  ignore_case = TRUE,
  optimize_regex = TRUE)


compund_sentence <- get_pop_tokens1(
  corp,
  create_compounds = T,
  compounds_at_level = "sentences",
  compounds_dict = popdictR::gruendl_terms,
  compounds_dict_glob = FALSE
)
saveRDS(compound_sentence, file = "compound_sentence2014.RDS")


########################### Create Dictionary
terms_df <- terms_df[terms_df$multiword == F,]
terms_ <- c(terms_df$Word, terms_multiword$compound) #change here!!!!!!!!!!!!!!!! for new regex words

terms_optimized <- regexhelpeR::optimize_regex_patterns(terms_)
terms_lazy <- regexhelpeR::make_all_regex_lazy(terms_optimized )



df_kwic <- kwic(compound_sentence, pattern = terms_lazy  , valuetype = "regex", window = 1, case_insensitive = T)

```



```{r}
#adding weights of dictionary terms
df_res <- merge(df_kmeans_aggr,as.data.frame(df_kwic), by = "pattern")
df_res$gruendl <- 1 #apply gruendl 


#aggregating weights by text

df_res <- df_res %>%
  select(docname,gruendl,weight)%>%
  group_by(df_res$docname)%>%
  reframe(
    weight = sum(weight),
  )

colnames(df_res) <- c("docname","gruendl","kmeans")


id2014 <- docvars(corp_2014)
id2014$docname <- rownames(id2014)

result <- merge(id2014, df_res, by = "docname")

summary <- result %>%
  group_by(party) %>%
  reframe(
    tokens  = sum(n_stokens),
    gruendl     = sum(dict_gruendl_2020) / sentences * 100,
    kmeans   = sum(kmeans) / sentences * 100,
  ) %>%
  ungroup



summary$gruendl <- scale(summary$gruendl,center = T)
summary$kmeans <- scale(summary$kmeans,center = T)
```




